package procurement.entity.risk;
// Generated Apr 14, 2018 1:58:23 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CiMigrations generated by hbm2java
 */
@Entity
@Table(name = "ci_migrations", catalog = "risk_manager_update")
public class CiMigrations implements java.io.Serializable {

	private long version;

	public CiMigrations() {
	}

	public CiMigrations(long version) {
		this.version = version;
	}

	@Id

	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

}
