package procurement.entity.risk;
// Generated Apr 14, 2018 1:58:23 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fitness generated by hbm2java
 */
@Entity
@Table(name = "fitness", catalog = "risk_manager_update")
public class Fitness implements java.io.Serializable {

	private Integer		id;
	private Projects	projects;
	private Integer		risk;
	private Integer		method;
	private Integer		financialImpact;
	private Integer		riskLevel;
	private int			cost;
	private int			diff;
	private int			priority;
	private int			time;
	private Date		createdAt;
	private int			deleted;

	public Fitness() {
	}

	public Fitness(Projects projects, int cost, int diff, int priority, int time, int deleted) {
		this.projects = projects;
		this.cost = cost;
		this.diff = diff;
		this.priority = priority;
		this.time = time;
		this.deleted = deleted;
	}

	public Fitness(Projects projects, Integer risk, Integer method, Integer financialImpact, Integer riskLevel,
			int cost, int diff, int priority, int time, Date createdAt, int deleted) {
		this.projects = projects;
		this.risk = risk;
		this.method = method;
		this.financialImpact = financialImpact;
		this.riskLevel = riskLevel;
		this.cost = cost;
		this.diff = diff;
		this.priority = priority;
		this.time = time;
		this.createdAt = createdAt;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@Column(name = "risk")
	public Integer getRisk() {
		return this.risk;
	}

	public void setRisk(Integer risk) {
		this.risk = risk;
	}

	@Column(name = "method")
	public Integer getMethod() {
		return this.method;
	}

	public void setMethod(Integer method) {
		this.method = method;
	}

	@Column(name = "financial_impact")
	public Integer getFinancialImpact() {
		return this.financialImpact;
	}

	public void setFinancialImpact(Integer financialImpact) {
		this.financialImpact = financialImpact;
	}

	@Column(name = "risk_level")
	public Integer getRiskLevel() {
		return this.riskLevel;
	}

	public void setRiskLevel(Integer riskLevel) {
		this.riskLevel = riskLevel;
	}

	@Column(name = "cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	@Column(name = "diff", nullable = false)
	public int getDiff() {
		return this.diff;
	}

	public void setDiff(int diff) {
		this.diff = diff;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "deleted", nullable = false)
	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

}
