package procurement.entity.risk;
// Generated Apr 14, 2018 1:58:23 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IonLoginAttempts generated by hbm2java
 */
@Entity
@Table(name = "ion_login_attempts", catalog = "risk_manager_update")
public class IonLoginAttempts implements java.io.Serializable {

	private Integer	id;
	private String	ipAddress;
	private String	login;
	private Integer	time;
	private Integer	deleted;

	public IonLoginAttempts() {
	}

	public IonLoginAttempts(String ipAddress, String login) {
		this.ipAddress = ipAddress;
		this.login = login;
	}

	public IonLoginAttempts(String ipAddress, String login, Integer time, Integer deleted) {
		this.ipAddress = ipAddress;
		this.login = login;
		this.time = time;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ip_address", nullable = false, length = 15)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "login", nullable = false, length = 100)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "time")
	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	@Column(name = "deleted")
	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

}
