package procurement.entity.risk;
// Generated Apr 14, 2018 1:58:23 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IonUsersGroups generated by hbm2java
 */
@Entity
@Table(name = "ion_users_groups", catalog = "risk_manager_update", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "group_id" }))
public class IonUsersGroups implements java.io.Serializable {

	private Integer	id;
	private int		userId;
	private int		groupId;
	private Integer	deleted;

	public IonUsersGroups() {
	}

	public IonUsersGroups(int userId, int groupId) {
		this.userId = userId;
		this.groupId = groupId;
	}

	public IonUsersGroups(int userId, int groupId, Integer deleted) {
		this.userId = userId;
		this.groupId = groupId;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "deleted")
	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

}
