/*
 * To change this license header, choose License Headers in Fitness Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procurement.ui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import procurement.builder.FitnessBuilder;
import procurement.controller.FitnessController;
import procurement.controller.ProjectController;
import procurement.entity.risk.Fitness;
import procurement.entity.risk.Projects;

/**
 *
 * @author nguyennam
 */
public class RiskSolver extends javax.swing.JPanel {

    ArrayList<Fitness> fitnesses;
    ArrayList<Projects> projects;
    
    /**
     * Creates new form RiskSolver
     */
    public RiskSolver() {
        initComponents();
        updateTable();
        procurement.RiskSolver riskSolver = new procurement.RiskSolver();
    }

    public void startStatus(){
        newBtn.setEnabled(true);
        deleteBtn.setEnabled(false);
        updateBtn.setEnabled(false);
    }
    public void editStatus(){
        newBtn.setEnabled(false);
        deleteBtn.setEnabled(true);
        updateBtn.setEnabled(true);
    }
    
    public void resetFields(){
        idLb.setText("");
        costCb.setSelectedIndex(0);
        diffCb.setSelectedIndex(0);
        financialCb.setSelectedIndex(0);
        methodCb.setSelectedIndex(0);
        priorityCb.setSelectedIndex(0);
        projectsCb.setSelectedIndex(0);
        riskCb.setSelectedIndex(0);
        riskLevelCb.setSelectedIndex(0);
        timeCb.setSelectedIndex(0);
    }
    public void setFitnessOnTable(Fitness fitness){

        idLb.setText(String.valueOf(fitness.getId()));
        costCb.setSelectedIndex(fitness.getCost());
        diffCb.setSelectedIndex(fitness.getDiff());
        financialCb.setSelectedIndex(fitness.getFinancialImpact());
        methodCb.setSelectedIndex(fitness.getMethod());
        priorityCb.setSelectedIndex(fitness.getPriority());
        projectsCb.setSelectedItem(fitness.getProjects().getName());
        riskCb.setSelectedIndex(fitness.getRisk());
        riskLevelCb.setSelectedIndex(fitness.getRiskLevel());
        timeCb.setSelectedIndex(fitness.getTime());
    }
    public Fitness getFitnessFromTable(){
        //need to fix
        Fitness fitness = new FitnessBuilder()
                .addId(Integer.valueOf(idLb.getText()))
                .addProjects(projects.get(projectsCb.getSelectedIndex()))
                .addRisk(riskCb.getSelectedIndex())
                .addMethod(methodCb.getSelectedIndex())
                .addFinancialImpact(financialCb.getSelectedIndex())
                .addRiskLevel(riskLevelCb.getSelectedIndex())
                .addCost(costCb.getSelectedIndex())
                .addDiff(diffCb.getSelectedIndex())
                .addPriority(priorityCb.getSelectedIndex())
                .addTime(timeCb.getSelectedIndex())
                .build();
        return fitness;
    }
    
    public void updateTable(){
        DefaultTableModel model = (DefaultTableModel) fitnessTable.getModel();
        model.setRowCount(0);
        fitnesses = FitnessController.index();
        for (int i = 0; i < fitnesses.size(); i++) {
            Fitness tempFitness = (Fitness) fitnesses.get(i);
            model.addRow(new Object[] {
                tempFitness.getId(), 
                tempFitness.getRisk(), 
                tempFitness.getMethod(), 
                tempFitness.getFinancialImpact(), 
                tempFitness.getRiskLevel(), 
                tempFitness.getCost(), 
                tempFitness.getDiff(), 
                tempFitness.getPriority(), 
                tempFitness.getTime(), 
                tempFitness.getProjects().getName()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fitnessTable = new javax.swing.JTable();
        newBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        riskCb = new javax.swing.JComboBox<>();
        financialCb = new javax.swing.JComboBox<>();
        methodCb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        riskLevelCb = new javax.swing.JComboBox<>();
        priorityCb = new javax.swing.JComboBox<>();
        diffCb = new javax.swing.JComboBox<>();
        costCb = new javax.swing.JComboBox<>();
        timeCb = new javax.swing.JComboBox<>();
        projectsCb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idLb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jPanel3.setPreferredSize(new java.awt.Dimension(755, 528));

        fitnessTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Risk", "Response", "Financial Impact", "Risk Level", "Cost", "Difficulty", "Priority", "Time", "Project"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        });
        fitnessTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fitnessTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(fitnessTable);

        newBtn.setText("Add New");
        newBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newBtnMouseReleased(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                updateBtnMouseReleased(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteBtnMouseReleased(evt);
            }
        });

        clearBtn.setText("Clear fields");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clearBtnMouseReleased(evt);
            }
        });

        String[] riskFitnessArr = new String[101];
        for (int i = 0; i < 101; i++) {
            riskFitnessArr[i] = String.valueOf(i);
        }
        riskCb.setModel(new javax.swing.DefaultComboBoxModel<>(riskFitnessArr));
        riskCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskCbActionPerformed(evt);
            }
        });

        String[] financialFitnessArr = new String[101];
        for (int i = 0; i < 101; i++) {
            financialFitnessArr[i] = String.valueOf(i);
        }
        financialCb.setModel(new javax.swing.DefaultComboBoxModel<>(financialFitnessArr));

        String[] methodFitnessArr = new String[101];
        for (int i = 0; i < 101; i++) {
            methodFitnessArr[i] = String.valueOf(i);
        }
        methodCb.setModel(new javax.swing.DefaultComboBoxModel<>(methodFitnessArr));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel2.setText("Configuration adjustment");

        String[] riskLevelFitnessArr = new String[101];
        for (int i = 0; i < 101; i++) {
            riskLevelFitnessArr[i] = String.valueOf(i);
        }
        riskLevelCb.setModel(new javax.swing.DefaultComboBoxModel<>(riskLevelFitnessArr));

        String[] priorityFitnessArr = new String[101];
        for (int i = 0; i < 101; i++) {
            priorityFitnessArr[i] = String.valueOf(i);
        }
        priorityCb.setModel(new javax.swing.DefaultComboBoxModel<>(priorityFitnessArr));

        String[] diffFitnessArr = new String[101];
        for (int i = 0; i < 101; i++) {
            diffFitnessArr[i] = String.valueOf(i);
        }
        diffCb.setModel(new javax.swing.DefaultComboBoxModel<>(diffFitnessArr));

        String[] costFitnessArr = new String[101];
        for (int i = 0; i < 101; i++) {
            costFitnessArr[i] = String.valueOf(i);
        }
        costCb.setModel(new javax.swing.DefaultComboBoxModel<>(costFitnessArr));

        String[] timeFitnessArr = new String[101];
        for (int i = 0; i < 101; i++) {
            timeFitnessArr[i] = String.valueOf(i);
        }
        timeCb.setModel(new javax.swing.DefaultComboBoxModel<>(timeFitnessArr));

        projects = ProjectController.index();
        String[] projectArray = new String[projects.size()];
        for (int i = 0; i < projects.size(); i++) {
            projectArray[i] = projects.get(i).getName();
        }
        //String[] tempArray = new String[]{"",""};
        projectsCb.setModel(new javax.swing.DefaultComboBoxModel<>(projectArray));

        jLabel1.setText("ID");

        jLabel3.setText("Risk");

        jLabel4.setText("Project");

        jLabel5.setText("Method");

        jLabel6.setText("Impact");

        jLabel7.setText("RiskLevel");

        jLabel8.setText("Cost");

        jLabel9.setText("Difficulty");

        jLabel10.setText("Priority");

        jLabel11.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14))
                            .addComponent(idLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(riskCb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(methodCb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(financialCb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(riskLevelCb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(costCb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diffCb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(priorityCb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeCb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addComponent(projectsCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(newBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(financialCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(riskLevelCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(riskCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(methodCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diffCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priorityCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectsCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void fitnessTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fitnessTableMouseClicked
        // TODO add your handling code here:

        int row = fitnessTable.rowAtPoint(evt.getPoint());
        DefaultTableModel model = (DefaultTableModel) fitnessTable.getModel();
        int id = (int) model.getValueAt(row, 0);
        Fitness fitness = (Fitness) FitnessController.show(id);
        setFitnessOnTable(fitness);
        editStatus();
    }//GEN-LAST:event_fitnessTableMouseClicked

    private void newBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBtnMouseReleased
        // TODO add your handling code here:
        Fitness fitness = new FitnessBuilder()
                .addProjects(projects.get(projectsCb.getSelectedIndex()))
                .addRisk(riskCb.getSelectedIndex())
                .addMethod(methodCb.getSelectedIndex())
                .addFinancialImpact(financialCb.getSelectedIndex())
                .addRiskLevel(riskLevelCb.getSelectedIndex())
                .addCost(costCb.getSelectedIndex())
                .addDiff(diffCb.getSelectedIndex())
                .addPriority(priorityCb.getSelectedIndex())
                .addTime(timeCb.getSelectedIndex())
                .build();
        FitnessController.create(fitness);
        updateTable();
    }//GEN-LAST:event_newBtnMouseReleased

    private void updateBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseReleased
        // TODO add your handling code here:
        FitnessController.update(getFitnessFromTable());
        updateTable();
    }//GEN-LAST:event_updateBtnMouseReleased

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseReleased
        // TODO add your handling code here:
        FitnessController.delete(Integer.valueOf(idLb.getText()));
        updateTable();
        resetFields();
    }//GEN-LAST:event_deleteBtnMouseReleased

    private void clearBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseReleased
        // TODO add your handling code here:
        resetFields();
    }//GEN-LAST:event_clearBtnMouseReleased

    private void riskCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riskCbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> costCb;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<String> diffCb;
    private javax.swing.JComboBox<String> financialCb;
    private javax.swing.JTable fitnessTable;
    private javax.swing.JLabel idLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> methodCb;
    private javax.swing.JButton newBtn;
    private javax.swing.JComboBox<String> priorityCb;
    private javax.swing.JComboBox<String> projectsCb;
    private javax.swing.JComboBox<String> riskCb;
    private javax.swing.JComboBox<String> riskLevelCb;
    private javax.swing.JComboBox<String> timeCb;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
