package risk.entity;
// Generated Apr 14, 2018 1:58:23 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Methods generated by hbm2java
 */
@Entity
@Table(name = "methods", catalog = "risk_manager_update")
public class Methods implements java.io.Serializable {

	private Integer			id;
	private Risks			risks;
	private String			code;
	private String			name;
	private int				cost;
	private int				diff;
	private int				time;
	private int				priority;
	private String			description;
	private Date			createdAt;
	private int				deleted;
	private Integer			efficiency;
	private Set<Conflicts>	conflictsesForMethod2Id	= new HashSet<Conflicts>(0);
	private Set<Conflicts>	conflictsesForMethod1Id	= new HashSet<Conflicts>(0);

	public Methods() {
	}

	public Methods(Risks risks, int cost, int diff, int time, int priority, int deleted) {
		this.risks = risks;
		this.cost = cost;
		this.diff = diff;
		this.time = time;
		this.priority = priority;
		this.deleted = deleted;
	}

	public Methods(Risks risks, String code, String name, int cost, int diff, int time, int priority,
			String description, Date createdAt, int deleted, Integer efficiency, Set<Conflicts> conflictsesForMethod2Id,
			Set<Conflicts> conflictsesForMethod1Id) {
		this.risks = risks;
		this.code = code;
		this.name = name;
		this.cost = cost;
		this.diff = diff;
		this.time = time;
		this.priority = priority;
		this.description = description;
		this.createdAt = createdAt;
		this.deleted = deleted;
		this.efficiency = efficiency;
		this.conflictsesForMethod2Id = conflictsesForMethod2Id;
		this.conflictsesForMethod1Id = conflictsesForMethod1Id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "risk_id", nullable = false)
	public Risks getRisks() {
		return this.risks;
	}

	public void setRisks(Risks risks) {
		this.risks = risks;
	}

	@Column(name = "code", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	@Column(name = "diff", nullable = false)
	public int getDiff() {
		return this.diff;
	}

	public void setDiff(int diff) {
		this.diff = diff;
	}

	@Column(name = "time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "deleted", nullable = false)
	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	@Column(name = "efficiency")
	public Integer getEfficiency() {
		return this.efficiency;
	}

	public void setEfficiency(Integer efficiency) {
		this.efficiency = efficiency;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "methodsByMethod2Id")
	public Set<Conflicts> getConflictsesForMethod2Id() {
		return this.conflictsesForMethod2Id;
	}

	public void setConflictsesForMethod2Id(Set<Conflicts> conflictsesForMethod2Id) {
		this.conflictsesForMethod2Id = conflictsesForMethod2Id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "methodsByMethod1Id")
	public Set<Conflicts> getConflictsesForMethod1Id() {
		return this.conflictsesForMethod1Id;
	}

	public void setConflictsesForMethod1Id(Set<Conflicts> conflictsesForMethod1Id) {
		this.conflictsesForMethod1Id = conflictsesForMethod1Id;
	}

}
