package risk.entity;
// Generated Apr 14, 2018 1:58:23 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects", catalog = "risk_manager_update")
public class Projects implements java.io.Serializable {

	private Integer			id;
	private String			code;
	private String			name;
	private String			description;
	private Date			createdAt;
	private Integer			finished;
	private int				deleted;
	private Set<Conflicts>	conflictses	= new HashSet<Conflicts>(0);
	private Set<Fitness>	fitnesses	= new HashSet<Fitness>(0);
	private Set<Risks>		riskses		= new HashSet<Risks>(0);

	public Projects() {
	}

	public Projects(int deleted) {
		this.deleted = deleted;
	}

	public Projects(String code, String name, String description, Date createdAt, Integer finished,
			int deleted, Set<Conflicts> conflictses, Set<Fitness> fitnesses, Set<Risks> riskses) {
		this.code = code;
		this.name = name;
		this.description = description;
		this.createdAt = createdAt;
		this.finished = finished;
		this.deleted = deleted;
		this.conflictses = conflictses;
		this.fitnesses = fitnesses;
		this.riskses = riskses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "finished")
	public Integer getFinished() {
		return this.finished;
	}

	public void setFinished(Integer finished) {
		this.finished = finished;
	}

	@Column(name = "deleted", nullable = false)
	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Conflicts> getConflictses() {
		return this.conflictses;
	}

	public void setConflictses(Set<Conflicts> conflictses) {
		this.conflictses = conflictses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Fitness> getFitnesses() {
		return this.fitnesses;
	}

	public void setFitnesses(Set<Fitness> fitnesses) {
		this.fitnesses = fitnesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Risks> getRiskses() {
		return this.riskses;
	}

	public void setRiskses(Set<Risks> riskses) {
		this.riskses = riskses;
	}

}
