package risk.entity;
// Generated Apr 14, 2018 1:58:23 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "risk_manager_update")
public class Users implements java.io.Serializable {

	private Integer	id;
	private String	ipAddress;
	private String	username;
	private String	name;
	private String	password;
	private String	salt;
	private String	email;
	private String	avatar;
	private String	activationCode;
	private String	forgottenPasswordCode;
	private Integer	forgottenPasswordTime;
	private String	rememberCode;
	private int		createdOn;
	private Integer	lastLogin;
	private Boolean	active;
	private int		deleted;

	public Users() {
	}

	public Users(String ipAddress, String username, String password, String salt, String email, int createdOn,
			int deleted) {
		this.ipAddress = ipAddress;
		this.username = username;
		this.password = password;
		this.salt = salt;
		this.email = email;
		this.createdOn = createdOn;
		this.deleted = deleted;
	}

	public Users(String ipAddress, String username, String name, String password, String salt, String email,
			String avatar, String activationCode, String forgottenPasswordCode, Integer forgottenPasswordTime,
			String rememberCode, int createdOn, Integer lastLogin, Boolean active, int deleted) {
		this.ipAddress = ipAddress;
		this.username = username;
		this.name = name;
		this.password = password;
		this.salt = salt;
		this.email = email;
		this.avatar = avatar;
		this.activationCode = activationCode;
		this.forgottenPasswordCode = forgottenPasswordCode;
		this.forgottenPasswordTime = forgottenPasswordTime;
		this.rememberCode = rememberCode;
		this.createdOn = createdOn;
		this.lastLogin = lastLogin;
		this.active = active;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ip_address", nullable = false, length = 16)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "username", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 80)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "salt", nullable = false, length = 40)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "avatar")
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "activation_code", length = 40)
	public String getActivationCode() {
		return this.activationCode;
	}

	public void setActivationCode(String activationCode) {
		this.activationCode = activationCode;
	}

	@Column(name = "forgotten_password_code", length = 40)
	public String getForgottenPasswordCode() {
		return this.forgottenPasswordCode;
	}

	public void setForgottenPasswordCode(String forgottenPasswordCode) {
		this.forgottenPasswordCode = forgottenPasswordCode;
	}

	@Column(name = "forgotten_password_time")
	public Integer getForgottenPasswordTime() {
		return this.forgottenPasswordTime;
	}

	public void setForgottenPasswordTime(Integer forgottenPasswordTime) {
		this.forgottenPasswordTime = forgottenPasswordTime;
	}

	@Column(name = "remember_code", length = 40)
	public String getRememberCode() {
		return this.rememberCode;
	}

	public void setRememberCode(String rememberCode) {
		this.rememberCode = rememberCode;
	}

	@Column(name = "created_on", nullable = false)
	public int getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(int createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "last_login")
	public Integer getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Integer lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "deleted", nullable = false)
	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

}
